[package]
name = "memwal"
edition = "2024"
authors = ["CommandOSS"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.59.0" }

[addresses]
memwal = "0x0"
memwal_v2 = "0x0"

[dev-addresses]

[dev-dependencies]
