-- services/server/migrations/011_memory_read_api_backfill_updated_at.sql
--
-- WALM-295: this file USED to be a single unbatched
-- `UPDATE vector_entries SET updated_at = created_at WHERE updated_at
-- IS NULL;`. On a real-sized table that single statement can run long
-- enough to hit a statement/idle timeout; Postgres rolls back the
-- ENTIRE UPDATE atomically on timeout (there is no partial-UPDATE
-- commit), which panics `VectorDb::new()` on the way out. Under
-- Railway's restart policy that becomes a crash-loop with zero net
-- progress: restart -> reconnect -> same unbatched UPDATE -> same
-- timeout, forever. LIVE-CONFIRMED against the dev DB (113k rows).
--
-- The fix has to be batched with each batch committing independently,
-- which means it cannot be a plain migration file: Postgres does not
-- allow COMMIT inside a `DO $$ ... $$` block (or any single statement)
-- run via `raw_sql`, so there is no way to express "loop, commit,
-- repeat" as SQL text alone. The backfill now lives in Rust as
-- `backfill_updated_at()` in `db.rs`, invoked from `VectorDb::new()`
-- after migration 010 and before migration 012 (which requires no NULL
-- rows remain). See that function's doc comment for the full
-- explanation.
--
-- This file is kept (rather than deleted) purely so migration numbering
-- and history stay intact -- every other migration file is referenced
-- by number in comments elsewhere (e.g. 010's header). Its body is now
-- a no-op.

SELECT 1;
